# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  web:      'src/CentralLogger/CentralLogger.Azure.csproj'
  provider: 'src/CentralLogProvider/CentralLogProvider.csproj'
  test:     'tests/CentralLogger.Tests/CentralLogger.Tests.csproj'

steps:
- script: dotnet test $(test)
  displayName: "Run Unit Test"

- script: dotnet publish $(web) --configuration $(buildConfiguration)  --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish Web Assets'

- script: dotnet pack $(provider) --configuration $(buildConfiguration)  --output $(Build.ArtifactStagingDirectory)
  displayName: 'Create NuGet package'

- task: PublishBuildArtifacts@1
- task: NodeTool@0
  inputs:
    version: '8.x'
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.300'